#DO NOT RUN use gendoc.sh please.

#echo "generating doc.go for $1"
echo // DO NOT EDIT GENERATED by misc/gendoc.sh in repo root > doc.go
echo   >> doc.go
echo /\* >> doc.go
$1 &>> doc.go
echo \*/ >> doc.go
echo package main >> doc.go
#echo "gofmt -w doc.go for $1"
gofmt -w doc.go
lister=`go list`
godoc $lister  > README